# Generated by Django 3.0.3 on 2020-05-20 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=48),
            preserve_default=False,
        ),
    ]
